
language: php

sudo: true

# Cache composer packages so "composer install" is faster
cache:
  directories:
  - $HOME/.composer/cache

php:
  - 7.1

#env:
#  global:
#  -

before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi

install:
  - composer install
  - composer require --dev phpunit/phpunit
  - composer require --dev satooshi/php-coveralls

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/coverage-clover.xml

after_success:
  php vendor/bin/coveralls -v --config .coveralls.yml;

notifications:
  email: mr.ahmed_samer@yahoo.com